# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: test-kecilin-be
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_URI: mongodb://database:27017 # example: mongodb://database:27017
      JWT_SECRET: testkecilin
      JWT_EXPIRES: 12h 
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'